### ISSUE TITLE
EXCEPTION: Uncaught (in promise): Error: Unsupported file 254

### ISSUE THREAD

**Issue by svillagracia** [DxCx/ts-xlsx#3]
I am using Angular-CLI to build out a spreadsheet reading service for my application. I'm receiving this error:
`error_handler.js:47EXCEPTION: Uncaught (in promise): Error: Unsupported file 254
Error: Unsupported file 254
    at Object.readSync [as read] (http://localhost:4200/main.bundle.js:101855:19)
    at SpreadsheetService.readBook (http://localhost:4200/main.bundle.js:90151:66)
    at http://localhost:4200/main.bundle.js:49346:31
    at SafeSubscriber._next (http://localhost:4200/main.bundle.js:113:21)
    at SafeSubscriber.__tryOrSetError (http://localhost:4200/main.bundle.js:538:16)
    at SafeSubscriber.next (http://localhost:4200/main.bundle.js:480:27)
    at Subscriber._next (http://localhost:4200/main.bundle.js:431:26)
    at Subscriber.next (http://localhost:4200/main.bundle.js:395:18)
    at BehaviorSubject._subscribe (http://localhost:4200/main.bundle.js:23163:24)
    at BehaviorSubject.Observable.subscribe (http://localhost:4200/main.bundle.js:61:27)`

In my service, my code looks like this:
`import { Injectable } from '@angular/core';`
`import { read, IWorkBook } from 'ts-xlsx';`
`@Injectable()`
`export class SpreadsheetService {`
`  constructor() { }`
`  readBook() {`
`    let doc = './testing/formula_stress_test_ajax.xlsx';`
`    let wb: IWorkBook = read(doc);`
`    console.log(wb);`
`  }`
`}`

and I'm calling it in my controller inside of `ngOnInit`

`ngOnInit(): void {`
`    this.spreadSheet.readBook();`
`}`

I also tried using the `readFile` method and received a different error:
`EXCEPTION: Uncaught (in promise): TypeError: _fs.readFileSync is not a function
TypeError: _fs.readFileSync is not a function
    at readSync (http://localhost:4200/main.bundle.js:101846:68)
    at readFileSync (http://localhost:4200/main.bundle.js:101862:10)
    at SpreadsheetService.readBook (http://localhost:4200/main.bundle.js:90151:90)
    at http://localhost:4200/main.bundle.js:49346:31
    at SafeSubscriber._next (http://localhost:4200/main.bundle.js:113:21)
    at SafeSubscriber.__tryOrSetError (http://localhost:4200/main.bundle.js:538:16)
    at SafeSubscriber.next (http://localhost:4200/main.bundle.js:480:27)
    at Subscriber._next (http://localhost:4200/main.bundle.js:431:26)
    at Subscriber.next (http://localhost:4200/main.bundle.js:395:18)
    at BehaviorSubject._subscribe (http://localhost:4200/main.bundle.js:23163:24)`

Currently, I'm only trying to `console.log` a test file.

**Comment by DxCx** [comment]
hmm, looks like you are trying to open filesystem file from the client and not the server.
it should work for the server, but for the client, what i did is to implement file upload (there was a ng2 component on npm) which will give me a blob of the data, and then used it as the source worksheet, because filesystem is not accessible.

**Comment by DxCx** [comment]
here is the RxJs pipe i've built:
```typescript
this._parsedFiles$ = super.getObservable()
   .do((file: File) => {
       if ( ALLOWED_MIME_TYPES.indexOf(file.type) >= 0 ) {
           return;
       }
       throw new Error('Invalid file provided!');
   })
   .switchMap((file: File) => {
       return new Observable<any>((observer) => { // TODO: Type
           let reader: FileReader = new FileReader();
            reader.onload = (e) => {
                observer.next((e.target as any).result);
            };

            reader.readAsBinaryString(file);
            return () => {
                reader.abort();
            };
        });
    }).map((value: string) => { // TODO: Type
        return XLSX.read(value, {type: 'binary'});
    }).map((wb: XLSX.IWorkBook) => {
        return wb.SheetNames.map((sheetName: string) => {
            let sheet: XLSX.IWorkSheet = wb.Sheets[sheetName];
            return XLSX.utils.sheet_to_json(sheet);
        });
    }).map((results: Array<any>) => {
        return {result: 'success', payload: results};
    })
```

**Comment by svillagracia** [comment]
Thanks, is it a specific module, or do any of them work with the pipe?

**Comment by DxCx** [comment]
I just used [rxjs](http://reactivex.io/rxjs/) because of the design of the code i used it with.
it is not a requirement to use rxjs inorder to support the xls, i paste it that way because that is the example i have, and it shows the actual functions of the library.

**Comment by svillagracia** [comment]
Apologies, I wasn't being very clear. I meant to ask if there was a specific file uploader module you were using along with the pipe?

**Comment by DxCx** [comment]
i used this as a base: https://github.com/valor-software/ng2-file-upload
but i modified it alot for my usage... (eventually i created a table that you can drop xls into it and it will show the xls content)

**Comment by svillagracia** [comment]
So, once the uploader is implemented, did you pass it back to the API first, then receive a blob of the data from the API? I, ideally, would like to parse the data on the front end and do some validations on it before passing it back to the API first. I'm trying to figure out if that's a possibility.

**Comment by DxCx** [comment]
yeah, my idea was to parse and load the data on the front-end (into a table).
the table can be further manipulated on the UI.
then when submit is pressed, the data is sent to the sever as JSON object.
